### ISSUE TITLE
Testing met security, hoe moeten we de @Before en @After doen?

### ISSUE THREAD

**Issue by boyenn** [boyenn/EntMob6SpringBackend#3]
Stel dat we een service hebben met Method Security : 

(snippet)
```
@Service
public class AccountService {

    @Autowired
    private AccountRepository accountRepository;
    @PreAuthorize("hasRole('ROLE_ADMIN')")
    public Account addAccount(Account account){
        return accountRepository.save(account);

    }

    @PreAuthorize("hasRole('ROLE_ADMIN')")
    public void deleteAll() {
        accountRepository.deleteAll();
    }
}
```

En we willen deze testen of de security werkt : 
```
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
@ContextConfiguration
public class AccountServiceTest {
    @Autowired
    private AccountService accountService;
    @Before
    @WithMockUser(roles = {"USER","ADMIN"})
    public void setUp() throws Exception {
        accountService.deleteAll();
        List<String> roles = new ArrayList<>();
        roles.add("USER");
        roles.add("ADMIN");
        Account startUser = new Account("startUser","startPassword",true,roles);
        accountService.addAccount(startUser);
    }

    @After
 @WithMockUser(roles = {"USER","ADMIN"})
    public void tearDown() throws Exception {
        accountService.deleteAll();
    }

    @Test
    @WithMockUser(roles = {"USER","ADMIN"})
    public void addAccountWithAdmin() throws Exception {
        TestCreateUSer();

    }


    @Test(expected = AccessDeniedException.class)
    @WithMockUser(roles = {"USER"})
    public void addAccountWithUser(){
        TestCreateUSer();

    }
    @Test(expected = AuthenticationCredentialsNotFoundException.class)
    public void addAccountWithoutUser(){
        TestCreateUSer();

    }
    private void TestCreateUSer() {
        List<String> roles = new ArrayList<>();
        roles.add("USER");
        Account normalUser = new Account("testUser","testPassword",true,roles);
        Account createdUser = accountService.addAccount(normalUser);
        assertEquals(normalUser.getPassword(),createdUser.getPassword());
        assertEquals(normalUser.getUsername(),createdUser.getUsername());
        assertEquals(normalUser.getRoles(),createdUser.getRoles());
    }


}
```

Testen addAccountWithoutUser en addAccountWithUser falen omdat ze de expected exception krijgen, maar in de  @Before of @After omdat deze methodes aanroepen die secured zijn, dus ook al is de exception expected, de test faalt... (bijvoorbeeld : )

```
org.springframework.security.access.AccessDeniedException: Access is denied

	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at be.boyenvaesen.Services.AccountService$$EnhancerBySpringCGLIB$$f437e0a.deleteAll(<generated>)
	at be.boyenvaesen.Services.AccountServiceTest.setUp(AccountServiceTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
...
```

Hoe kunnen we dit dan testen? Waarom kan ik mijn @Before of @After niet authorizeren?

PS : addAccountWithAdmin werkt well

**Comment by boyenn** [comment]
@Sch3lp

**Comment by Sch3lp** [comment]
Dat komt omwille van het feit dat @Before en @After wel _rond_ de uitvoerende test method staan, maar dat wordt at runtime geproxied door de `SpringJunitRunner`, waardoor ge zoiets krijgt (in pseudocode):

```java
@Test(expected = AccessDeniedException.class)
@WithMockUser(roles = {"USER"})
public void addAccountWithUser() {
    setUp();
    TestCreateUSer();
    tearDown();
}
```

Dat komt doordat er iets moet zijn dat die `@WithMockUser` moet kunnen interpreteren.

Hier is in ieder geval iets waardoor ge meer inzicht kunt krijgen in dit probleem: http://www.mscharhag.com/java/understanding-junits-runner-architecture


Maar ge kunt dit probleem ook anders bekijken.

Uw _Class under Test_ is de `AccountService`, en de enige momenten dat ge die hoort op te roepen in uw test is in de test method zelf; nadat ge de nodige set up gedaan hebt om het geval dat ge wilt testen ook effectief te kunnen testen.

Voor de `addAccountWithAdmin` wilt ge dat er al een _Admin_ bestaat (om 1 of andere reden), en die zet ge op in de `@Before`. Maar, om die set up te doen doet ge dat ook via de `AccountService` zelf.

Dat is alvast niet goed. Die set up moet ge doen door via de `AccountRepository` (of via de entitymanager) een nieuwe _Account_ aan te maken. Zodat ge uw _Class under Test_ enkel in de test method zelf test.


De tweede issue is dat die setup die ge aan het doen zijt om die _Admin_ aan te maken overbodig is denk ik.

Ik denk, dat gij denkt, dat ge die set up nodig hebt om een user te hebben waarmee ge het _HappyPath_ (het succesvol aanmaken van een nieuwe _Account_) kunt uitvoeren. Maar daarvoor dient die `@WithMockUser` annotatie net voor.

Kan zijn dat ik ergens iets over het hoofd zie he. Maar dus het enige dat in uwe setUp en tearDown hoort te staan is dat verwijderen van in de test aangemaakte _Account_s.

PS: Als ge die triple backticks gebruikt om code te posten kunt ge daar de taal achter zetten waardoor ge syntax highlighting krijgt. Like so:

    ```java
    derpyderpderp
    ```

**Comment by boyenn** [comment]
Copy that,

het gedeelte 

```java
  List<String> roles = new ArrayList<>();
        roles.add("USER");
        roles.add("ADMIN");
        Account startUser = new Account("startUser","startPassword",true,roles);
        accountService.addAccount(startUser);
```

in de @Before was oude code , sorry dat deze er nog bijstond , want deze heeft voor confusion gezorgd.

Het ging mij vooral om de 
```java
 accountService.deleteAll();
```

Deze moet wel aangeroepen voor en na iedere test om zeker te zijn dat iedere test met dezelfde start environment begint.

U zegt dan : 

> Die set up moet ge doen door via de AccountRepository (of via de entitymanager) een nieuwe Account aan te maken. Zodat ge uw Class under Test enkel in de test method zelf test.

Hier lees ik dan ook uit dat deleteAll() ook rechstreekt in de repository moet aangeroepen worden.

Dit klinkt inderdaad logisch, maar is dit dan geen beschendiging van ons eigen design principe ? Waarbij je enkel ooit de service aanroept en nooit de repository rechtstreeks?

Stel dat de deleteAll in de repository niet werkt om de een of andere redenen, is dit voor ons nu toch onbelangrijk ? We zijn toch alleen aan het kijken of de service wel of niet werkt. De repository is geautowired. Is het niet de bedoeling dat wij ervanuitgaan dat wij niet weten welke repository is geautowired in AccountService (Bijv MongoRepo of CrudRepo) , zolang de service maar zijn best doet dit op te lossen?

Dit word erg omslachtig en ik kom niet goed uit mijn woorden, mijn excuses daarvoor.

Ik ga het proberen korter samen te vatten:

Als ik de repository rechtstreeks aanroep in mijn setup van mijn service test, en ik verander later de default bean voor die repository, breekt deze test. Dan moet ik terug naar mijn service testen gaan en daar de repository aanpassen

Mij lijkt het logischer om de service methode aan te roepen, want als dan de implementatie van de repository veranderd,  moet er geen aanpassing aan de service test gebeuren. Wat mij logisch lijkt want de test gaat alleen over de service en niet over de repository.

Denk ik fout hier ? Zie ik misschien het plaatje van repository en Service interfaces fout?

**Comment by boyenn** [comment]
@Sch3lp

**Comment by Sch3lp** [comment]
Daarmee dat ik ook voorstelde van eventueel via de EntityManager rechtstreeks de entity te saven of te deleten.
Uw redenering klopt wel, maar in dit geval (voor enkel die AccountServiceTest), is het gebruik van die repo wel geisoleerd genoeg.
Allez, ge hebt nu twee gebruiken van die repo wel. Maar het is best wel handig dat ge uw repo ook voor die test kunt gebruiken.
Vooral omdat de "impl" van die repo in dit geval nie gaat veranderen tenzij ge gene spring-data meer gaat gebruiken. Ge moet daar wat pragmatisch in zijn.
In ieder geval, als ge het wél afzonderlijk van mekaar wilt hebben in uw integratietesten, gaat ge een ander frameworkske nodig hebben om records naar een database weg te schrijven en die achteraf terug op te kuisen.

Maar dan hebt ge dus ook altijd dubbel werk wanneer uw entities veranderen want dan moet ge het aanpassen in uw hibernate mapping, en in uw tes persistence frameworkske.



On Wed, Nov 2, 2016 at 6:09 PM +0100, "boyenn" <notifications@github.com> wrote:












Copy that,



het gedeelte 

  List<String> roles = new ArrayList<>();
        roles.add("USER");
        roles.add("ADMIN");
        Account startUser = new Account("startUser","startPassword",true,roles);
        accountService.addAccount(startUser);



in de @Before was oude code , sorry dat deze er nog bijstond , want deze heeft voor confusion gezorgd.



Het ging mij vooral om de 

 accountService.deleteAll();



Deze moet wel aangeroepen voor en na iedere test om zeker te zijn dat iedere test met dezelfde start environment begint.



U zegt dan : 




Die set up moet ge doen door via de AccountRepository (of via de entitymanager) een nieuwe Account aan te maken. Zodat ge uw Class under Test enkel in de test method zelf test.




Hier lees ik dan ook uit dat deleteAll() ook rechstreekt in de repository moet aangeroepen worden.



Dit klinkt inderdaad logisch, maar is dit dan geen beschendiging van ons eigen design principe ? Waarbij je enkel ooit de service aanroept en nooit de repository rechtstreeks?



Stel dat de deleteAll in de repository niet werkt om de een of andere redenen, is dit voor ons nu toch onbelangrijk ? We zijn toch alleen aan het kijken of de service wel of niet werkt. De repository is geautowired. Is het niet de bedoeling dat wij ervanuitgaan dat wij niet weten welke repository is geautowired in AccountService (Bijv MongoRepo of CrudRepo) , zolang de service maar zijn best doet dit op te lossen?



Dit word erg omslachtig en ik kom niet goed uit mijn woorden, mijn excuses daarvoor.



Ik ga het proberen korter samen te vatten:



Als ik de repository rechtstreeks aanroep in mijn setup van mijn service test, en ik verander later de default bean voor die repository, breekt deze test. Dan moet ik terug naar mijn service testen gaan en daar de repository aanpassen



Mij lijkt het logischer om de service methode aan te roepen, want als dan de implementatie van de repository veranderd,  moet er geen aanpassing aan de service test gebeuren. Wat mij logisch lijkt want de test gaat alleen over de service en niet over de repository.



Denk ik fout hier ? Zie ik misschien het plaatje van repository en Service interfaces fout?

**Comment by boyenn** [comment]
Ok ! Denk het te begrijpen.

Het werkt in ieder geval met de repository aan te roepen.

Snel een klein ongerelateerd vraagje, aangezien jij meer ervaring hebt met intelliJ.

Ik ben de overstap aan het proberen te maken, en het lijkt te lukken maar het heeft een raar trekje

Als ik de Autowired notatie gebruik in test classes geeft het me een rare precompile warning :
Could not autowire. No beans of .. type found 

Deze warning had ik in netbeans niet, en het lijkt mij een false positive te zijn omdat intelliJ misschien de applicationcontext niet ziet in test classes? 

Heeft u dit al eens meegemaakt/ moet ik me hier zorgen om maken

Ter verklaring: de code werkt wel

**Comment by boyenn** [comment]
Nevermind, fixed

**Comment by Sch3lp** [comment]
👍
Nu nog inchecken zeker? 😄
